#!/usr/bin/env python3
"""Generate the LaTeX report body for CPE 333 PS7.

    python3 scripts/make_latex.py

WHAT THIS WRITES
    latex/generated/*        always overwritten -- never edit these by hand
    latex/discussion/*.tex   written ONLY if absent -- the prose is safe

The source and the transcripts are pulled in with \\lstinputlisting at compile
time, and the results tables are parsed out of results/ on every build, so no
number in the report is ever typed by hand.
"""
import io
import os
import re
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LATEX = os.path.join(ROOT, "latex")
GEN = os.path.join(LATEX, "generated")
DISC = os.path.join(LATEX, "discussion")

BLOCK = re.compile(r"^--- (.+), run (\d+) ---$")
TOTAL = re.compile(r"tickets sold: (\d+) for (\d+) seats, seats left: (-?\d+)")

QUOTED = set()   # transcripts the document actually shows


# --------------------------------------------------------------- parsing ---
def parse(rel):
    """[(label, run, first_line, last_line, body)] with 1-based line numbers."""
    with io.open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    blocks, cur = [], None
    for i, line in enumerate(lines, 1):
        m = BLOCK.match(line)
        if m:
            if cur:
                blocks.append(cur)
            cur = [m.group(1), int(m.group(2)), i, i, []]
        elif cur:
            cur[3] = i
            cur[4].append(line)
    if cur:
        blocks.append(cur)
    for b in blocks:                      # drop the blank line each block ends with
        while b[4] and not b[4][-1].strip():
            b[4].pop()
            b[3] -= 1
    return blocks


def totals(rel):
    """[(run, sold, seats, left)] for every run in a transcript."""
    rows = []
    for _, run, _, _, body in parse(rel):
        for line in body:
            m = TOTAL.search(line)
            if m:
                rows.append((run, int(m.group(1)), int(m.group(2)), int(m.group(3))))
    if not rows:
        raise SystemExit("make_latex.py: no totals in %s" % rel)
    return rows


# --------------------------------------------------------------- helpers ---
def listing(rel, style, caption, extra=""):
    return ("\\lstinputlisting[style=%s%s,caption={%s}]{../%s}"
            % (style, extra, caption, rel))


def needspace(lines):
    """Keep a transcript on one page: ask for its height, or give up if it
    could never fit (scriptsize is ~0.62 baselineskip; a page is ~50)."""
    need = int(lines * 0.62) + 3
    return r"\headroom" if need > 48 else r"\Needspace*{%d\baselineskip}" % need


def all_runs(rel, caption):
    """The listing, without its Needspace: sec() places that ahead of the
    section heading, so heading and transcript move to a new page together."""
    blocks = parse(rel)
    first, last = blocks[0][2], blocks[-1][3]
    QUOTED.add(rel)
    return listing(rel, "term", caption, ",firstline=%d,lastline=%d" % (first, last))


def run_lines(rel):
    blocks = parse(rel)
    return blocks[-1][3] - blocks[0][2] + 1


def totals_table(rel, caption):
    rows = totals(rel)
    out = [r"\begin{center}", r"\small", r"\begin{tabular}{@{}rrrr@{}}", r"\toprule",
           r"Run & Tickets sold & Oversold by & Seats left \\", r"\midrule"]
    for run, sold, seats, left in rows:
        out.append(r"%d & %s & %s & %d \\" % (run, "{:,}".format(sold),
                                             "{:,}".format(sold - seats), left))
    out += [r"\bottomrule", r"\end{tabular}",
            r"\captionof{table}{%s}" % caption, r"\end{center}"]
    return "\n".join(out)


def check_coverage():
    """Every transcript in results/ must appear in the document."""
    have = {"results/" + f for f in os.listdir(os.path.join(ROOT, "results"))
            if f.endswith(".txt")}
    missing = sorted(have - QUOTED)
    if missing:
        raise SystemExit("make_latex.py: captured but never shown: %s" % missing)


# ------------------------------------------------------------- structure ---
T1, T2, T3 = "results/task1.txt", "results/task2.txt", "results/task3.txt"
KEYS = ["program", "task1", "task2", "task3", "race"]


def build_body():
    out = ["% GENERATED by scripts/make_latex.py -- DO NOT EDIT", ""]

    def sec(title, key, blocks, transcript=None):
        # A section that opens with a transcript reserves room for heading and
        # transcript together, so the heading is never stranded at a page foot.
        # 4 lines covers the heading and its spacing.
        if transcript:
            out.append(needspace(run_lines(transcript) + 4))
        out.extend([r"\headroom", r"\section{%s}" % title, ""])
        out.extend(blocks)
        out.extend([r"\input{discussion/%s}" % key, ""])

    sec("The Program", "program", [
        listing("src/ps7.c", "csrc", r"Source: \texttt{ps7.c}"), ""])
    sec("Task 1: One Thread", "task1", [
        all_runs(T1, r"Seven runs of \texttt{./ps7 1}"), ""], transcript=T1)
    sec("Task 2: Several Threads, No Forced Context Switch", "task2", [
        all_runs(T2, r"Seven runs of \texttt{./ps7 4}"), "",
        totals_table(T2, "Final totals of task 2"), ""], transcript=T2)
    sec("Task 3: Forced Context Switch", "task3", [
        all_runs(T3, r"Seven runs of \texttt{./ps7 4 yield}"), "",
        totals_table(T3, "Final totals of task 3"), ""], transcript=T3)
    sec("Discussion", "race", [])

    check_coverage()
    with io.open(os.path.join(GEN, "body.tex"), "w", encoding="utf-8",
                 newline="\n") as fh:
        fh.write("\n".join(out) + "\n")


def build_discussion_stubs():
    """Written ONCE. Existing files are left completely alone."""
    created, kept = [], []
    for key in KEYS:
        path = os.path.join(DISC, "%s.tex" % key)
        if os.path.exists(path):
            kept.append(os.path.basename(path))
            continue
        with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("%% Discussion for %s -- never overwritten by make_latex.py.\n\n"
                     "\\todoprose{Not written yet.}\n" % key)
        created.append(os.path.basename(path))
    return created, kept


def main():
    if os.path.isdir(GEN):
        shutil.rmtree(GEN)
    os.makedirs(GEN)
    os.makedirs(DISC, exist_ok=True)
    build_body()
    created, kept = build_discussion_stubs()
    if created:
        print("created discussion stubs   : %s" % ", ".join(created))
    if kept:
        print("LEFT UNTOUCHED (your prose): %s" % ", ".join(kept))


if __name__ == "__main__":
    main()
